name: Deploy huipengjohnyao.com Personal Site to S3 + CloudFront

on:
    push:
      branches:
        - main

jobs:
    deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 20
            cache: 'npm'

        - name: Debug environment
          run: |
            pwd
            ls -la
            echo "Node version: $(node --version)"
            echo "NPM version: $(npm --version)"

        - name: Install dependencies
          run: |
            rm -rf node_modules package-lock.json
            npm install
            echo "Checking enhanced-resolve installation:"
            ls -la node_modules/enhanced-resolve/ || echo "enhanced-resolve not found"
            ls -la node_modules/enhanced-resolve/util/ || echo "enhanced-resolve/util not found"
  
        - name: Build React app
          run: npm run build
  
        - name: Sync to S3
          run: aws s3 sync build/ s3://${{ secrets.BUCKET_NAME }} --delete
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
  
        - name: Invalidate CloudFront
          run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}


